apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: rbd-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 5
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
      transaction.max.timeout.ms: 4000000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        class: disks
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: disks
  entityOperator:
    topicOperator: {}
    userOperator: {}