apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: access-parser-java
spec:
  image:
    name: wichtr/private:access-parser-java-latest
    pullPolicy: Always
    pullSecrets: 
      - name: regcred
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "600Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "600Mi"
        cpu: "200m"
  job:
    jarFile: /opt/access-parser-java-1.0.0.jar
    parallelism: 1
    args: 
      - --bootstrapServers
      - my-cluster-kafka-brokers.kafka.svc:9092
      - --consumerTopic
      - webserver-access
      - --producerTopic
      - webserver-access-cleaned
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
    taskmanager.memory.flink.size: "500 mb"
    state.backend: filesystem
    state.backend.incremental: "true"
    state.checkpoints.dir: file:///data/
    taskmanager.memory.managed.size: "0 mb"
