apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: latency-streaming
spec:
  image:
    name: wichtr/private:latency-streaming-latest
    pullPolicy: Always
    pullSecrets: 
      - name: regcred
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "600Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "600Mi"
        cpu: "200m"
  job:
    jarFile: /opt/latency-streaming-1.0.0.jar
    parallelism: 1
    args: 
      - --bootstrapServers
      - my-cluster-kafka-brokers.kafka.svc:9092
      - --consumerTopicWeb
      - webserver-access-cleaned
      - --consumerTopicClient
      - client-cleaned
      - --cassandraServers
      - cluster1-dc1-service.cass-operator.svc
      - --cassandraPort
      - "9042"
      - --cassandraUser
      - cluster1-superuser
      - --cassandraPassword
      - uGs9xxeDyOqftwcjuJm7CAeOWoLp1Tk8YztV3GdLLnzM8KgcOGIZrw
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
    taskmanager.memory.flink.size: "500 mb"
    state.backend: filesystem
    state.backend.incremental: "true"
    state.checkpoints.dir: file:///data/
    taskmanager.memory.managed.size: "0 mb"
