apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  labels:
    app: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - name: generator
        image: wichtr/private:loggen-latest
        imagePullPolicy: Always
        volumeMounts:
        - name: logstash-configmap
          mountPath: /etc/logstash-config
        - name: log-generator-configmap
          mountPath: /etc/log-generator-config
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: logstash-configmap
        configMap:
          name: logstash-config
      - name: log-generator-configmap
        configMap:
          name: log-generator-config