apiVersion: v1
kind: ConfigMap
metadata:
  name: log-generator-config
data:
  config.yml: |-
    webserver: /var/log/apache_access.log
    client: /var/log/client.log
    modes:
      - times: 100
        latency_level: 3
        intensity_level: 1
      - times: 100
        latency_level: 3
        intensity_level: 2
      - times: 100
        latency_level: 2
        intensity_level: 3
      - times: 100
        latency_level: 1
        intensity_level: 4
      - times: 10
        latency_level: 4
        intensity_level: 1