---

# installs kubernetes on cluster

- name: setup hosts
  hosts: all
  become: yes
  roles:
    - setup

- name: setup master
  hosts: masters
  become: yes
  roles:
    - master

- name: setup slaves
  hosts: slaves
  become: yes
  roles:
    - slave

- name: setup hosts
  hosts: masters
  roles:
    - kubernetes-storage-provisioner
    - kubernetes-kafka
    - kubernetes-flink-operator
    - kubernetes-cassandra-datastax
