version: '3'

services:
  cassandra:
    build: ./cassandra
    restart: always

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile_Development
    restart: always
    depends_on:
      - cassandra
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
    environment:
      CASSANDRA_SERVER: cassandra
      CASSANDRA_PORT: 9042

      
#  client:
#    image: node
#    restart: always
#    depends_on:
#      - server
#    ports:
#      - 3000:3000
#    volumes:
#      - ./client:/client
#    working_dir: /client
#    command: npm start