---
# vars file for cassandra-config

queries:
  - "CONSISTENCY QUORUM"
  - "CREATE KEYSPACE IF NOT EXISTS malicious WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };"
  - "CREATE TABLE IF NOT EXISTS malicious.result (date date,timestamp timestamp,value int,PRIMARY KEY (date, timestamp)) WITH CLUSTERING ORDER BY (timestamp ASC);"
  - "CREATE KEYSPACE IF NOT EXISTS latency WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };"
  - "CREATE TABLE IF NOT EXISTS latency.result (date date,timestamp timestamp,min bigint,max bigint,avg double,PRIMARY KEY (date, timestamp)) WITH CLUSTERING ORDER BY (timestamp ASC);"
  - "CREATE KEYSPACE IF NOT EXISTS popular WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };"
  - "CREATE TABLE IF NOT EXISTS popular.result (path text,timestamp timestamp,value int,PRIMARY KEY (path, timestamp)) WITH CLUSTERING ORDER BY (timestamp ASC);"

tables:
  - malicious
  - latency
  - popular