apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-role-binding-flink
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
