apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-client
  labels:
    app: visualization-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-client
  template:
    metadata:
      labels:
        app: visualization-client
    spec:
      containers:
      - name: visualization-client
        image: wichtr/private:visualization-client-latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: visualization-frontend
spec:
  type: NodePort
  selector: 
    app: visualization-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31013
